# playbooks/00_copy_tls_secret.yml -----------------------------------
- name: 🔒 Copiar certificado TLS al namespace ArgoCD
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: 📦 ¿Existe el Secret en argocd?
      command: >
        {{ kubectl_path }} --kubeconfig {{ kubeconfig_path }}
        get secret {{ tls_secret_name }} -n {{ argocd_namespace }}
      register: tls_in_argocd
      failed_when: false
      changed_when: false

    - name: 📤 Copiar Secret desde kube-system → argocd (si falta)
      shell: |
        {{ kubectl_path }} --kubeconfig {{ kubeconfig_path }} \
        get secret {{ tls_secret_name }} -n kube-system -o yaml | \
        sed "s/namespace: kube-system/namespace: {{ argocd_namespace }}/" | \
        {{ kubectl_path }} --kubeconfig {{ kubeconfig_path }} apply -f -
      when: "'NotFound' in tls_in_argocd.stderr"
      changed_when: true
