# playbooks\deploy_argocd.yml
---
- name: Desplegar ArgoCD vía Helm con Traefik Ingress
  hosts: controller
  become: true
  gather_facts: false
  vars_files:
    - group_vars/all.yml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  tasks:
    - name: Crear namespace de ArgoCD
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ argocd_namespace }}"

    - name: Agregar repositorio Helm de ArgoCD
      command: helm repo add argo https://argoproj.github.io/argo-helm
      register: argo_repo
      failed_when: argo_repo.rc != 0 and "already exists" not in argo_repo.stderr

    - name: Actualizar repositorios Helm
      command: helm repo update

    - name: Renderizar archivo values.yaml.j2
      template:
        src: templates/argocd/values.yaml.j2
        dest: /tmp/argocd-values.yaml

    - name: Instalar ArgoCD con Helm
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        chart_version: "{{ argocd_chart_version }}"
        release_namespace: "{{ argocd_namespace }}"
        create_namespace: false
        values_files:
          - /tmp/argocd-values.yaml
        kubeconfig: "{{ kubeconfig_path }}"